.SUFFIXES: .cxx .o

all : tthttpd.exe

tthttpd.exe : main.o httpd.o utils.o
	g++ -O2 -mtune=i686 -mthreads -o $@ main.o httpd.o utils.o -lws2_32

.cxx.o :
	g++ -O2 -mtune=i686 -mthreads -Wall -c $<

clean :
	rm *.o tthttpd
